const acousticModel = {
  Gibson: ['J-45', 'SJ-200', 'Hummingbird', 'Songwriter'],
  Martin: [
    'D-200',
    'D-45',
    'D-42',
    'D-28',
    'D-18',
    '000-42',
    '000-28',
    '00-28',
    '0-18',
    '00-18',
    '000-18',
  ],
  Taylor: [
    'PS14ce',
    'PS12ce',
    'K26ce',
    'K24ce',
    'K22ce',
    'K14ce',
    '914ce',
    '912ce',
  ],
  Yamaha: [
    'A Series',
    'L Series',
    'CSF',
    'FG Series',
    'F Series',
    'APX Series',
    'CPX Series',
  ],
  Takamine: [
    'Pro Series 1',
    'Pro Series 2',
    'Pro Series 3',
    'Pro Series 4',
    'Pro Series 5',
    'Pro Series 6',
    'Pro Series 7',
    'Signature Series',
    'Legacy Series',
    'Limited',
  ],
  Ovation: [],
  Guild: ['D-55'],
  Carvin: [],
  Gretsch: [],
  National: [],
  Tacoma: [],
} as const;

export default acousticModel;
