import { defaultContext, emptyContext, IFormContext } from '../../lib/context';

const formPresets: {
    [key: string]: { formState: IFormContext; otherState: IFormContext } & {
        name: string;
    };
} = {
    'Gibson Les Paul Custom': {
        name: 'Gibson Les Paul Custom',
        formState: {
            make: 'Gibson',
            model: 'Les Paul',
            subModel: 'Custom',
            year: '',
            finish: '',
            countryOfOrigin: 'USA',
            serial: '',
            condition: 'sel',
            weight: '',
            bodyType: 'Solid',
            bodyWood: 'Mahogany',
            scaleLength: '24.75"',
            neckJoint: 'Set Neck',
            neckWood: 'Mahogany',
            neckFinish: 'sel',
            fingerBoard: 'Ebony',
            radius: '12',
            neckProfile: 'Rounded',
            inlays: 'sel',
            nutWidth: '1.6875"',
            nut: 'Bone',
            frets: '22 Medium Jumbo',
            pickupNeck: '',
            pickupMiddle: '',
            pickupBridge: '',
            pickupConfiguration: 'sel',
            pickguard: 'sel',
            pots: '2-Volume, 2-Tone',
            coilTap: 'sel',
            pickupSwitch: '3-Way Toggle Switch',
            phaseSwitch: 'sel',
            killSwitch: 'sel',
            hardware: 'sel',
            tuningMachines: 'sel',
            bridge: 'ABR-1 Tune-O-Matic',
            knobs: 'sel',
            modifications: 'sel',
            otherFeatures: 'sel',
            stringGauge: '10-46',
            guitarCase: 'sel',
        },
        otherState: {
            make: '',
            model: '',
            subModel: '',
            year: '',
            finish: '',
            countryOfOrigin: '',
            serial: '',
            condition: '',
            weight: '',
            bodyType: '',
            bodyWood: '',
            scaleLength: '',
            neckJoint: '',
            neckWood: '',
            neckFinish: '',
            fingerBoard: '',
            radius: '',
            neckProfile: '',
            inlays: '',
            nutWidth: '',
            nut: '',
            frets: '',
            pickupNeck: '',
            pickupMiddle: '',
            pickupBridge: '',
            pickupConfiguration: '',
            pickguard: '',
            pots: '',
            coilTap: '',
            pickupSwitch: '',
            killSwitch: '',
            phaseSwitch: '',
            hardware: '',
            tuningMachines: '',
            bridge: '',
            knobs: '',
            modifications: '',
            otherFeatures: '',
            stringGauge: '',
            guitarCase: '',
        },
    },
    Clear: {
        formState: defaultContext,
        otherState: emptyContext,
        name: 'Clear',
    },
};
export default formPresets;
