const knobs = [
  'Black Top Hat',
  'White Top Hat',
  'Cream Top Hat',
  'Amber Top Hat',
  'Clear Top Hat',
  'Gold Top Hat',
  'Black Speed',
  'White Speed',
  'Amber Speed',
  'Gold Speed',
  'Clear Speed',
  'Knurled Chrome Dome',
  'Knurled Chrome',
  'Knurled Chrome Flat Top',
  'Knurled Black Dome',
  'Knurled Black',
  'Knurled Black Flat Top',
  'Knurled Gold Dome',
  'Knurled Gold',
  'Knurled Gold Flat Top',
  'Top Hat Reflector',
  'Witch Hat',
];

export default knobs;
