import model from './model';

const subModel = {
    Fender: {
        Stratocaster: [
            'American Standard',
            'American Deluxe',
            'American Ultra',
            'American Elite',
            "American Original '50s",
            'American Vintage',
            'American Performer',
            'Hardtail',
            'VG',
            'Masterbuilt',
        ],
        Telecaster: [
            'American Vintage',
            'American Performer',
            'American Professional',
            'Thinline Semihollow',
            'Hot Rod',
            'Masterbuilt',
        ],
        Esquire: [],
        Nocaster: [],
        Jaguar: [],
        Jazzmaster: ['American Vintage'],
    } as Record<typeof model['Fender'][number], string[]>,
    Gibson: {
        'Les Paul': [
            'Standard',
            'Custom',
            'Classic',
            'Studio',
            'Tribute',
            'Special',
            'Special Tribute',
            'Junior',
            "Standard '50s",
            "Standard '60s",
            "'70s Deluxe",
            'Modern',
        ],
        SG: [
            'Special',
            'Standard',
            'Tribute',
            "Standard '61",
            "Standard '61 Maestro Vibrola",
            "Standard '61 Sideways Vibrola",
            'Junior',
            'Modern',
        ],
        Firebird: ['I', 'III', 'V', 'VII'],
        Explorer: [],
        'Flying V': [],
        M3: [],
        'ES-335': [],
        'ES-339': [],
        'ES-347': [],
    } as Record<typeof model['Gibson'][number], string[]>,
    Jackson: {
        Dinky: [
            'DK1',
            'DK2',
            'DK2M',
            'DK2S',
            'DK2T',
            'DK2FF',
            'DK2FS',
            'DK3',
            'DR3',
            'DKMG',
            'DKMGT',
            'DXMG',
            'DKXT',
        ],
        Kelly: ['KE3', 'KE4', 'KV3'],
        'King V': [
            'KV',
            'KVT',
            'KV6',
            'KV7',
            'KV6Q',
            'KV7Q',
            'KVTMG',
            'KVXMG',
            'JS32',
            'JS32T',
        ],
        Monarkh: [],
        Rhoads: [],
        'San Dimas': [],
        'So-Cal': [],
        Soloist: ['SL1', 'SL2', 'SL2H', 'SLS', 'SL3', 'SL3R', 'SL3X'],
    } as Record<typeof model['Jackson'][number], string[]>,
    Charvel: {
        Dinky: [
            'DK1',
            'DK2',
            'DK2M',
            'DK2S',
            'DK2T',
            'DK2FF',
            'DK2FS',
            'DK3',
            'DR3',
            'DKMG',
            'DKMGT',
            'DXMG',
            'DKXT',
        ],
        Kelly: ['KE3', 'KE4', 'KV3'],
        'King V': [
            'KV',
            'KVT',
            'KV6',
            'KV7',
            'KV6Q',
            'KV7Q',
            'KVTMG',
            'KVXMG',
            'JS32',
            'JS32T',
        ],
        Monarkh: [],
        Rhoads: [],
        'San Dimas': [],
        'So-Cal': [],
        Soloist: ['SL1', 'SL2', 'SL2H', 'SLS', 'SL3', 'SL3R', 'SL3X'],
    } as Record<typeof model['Charvel'][number], string[]>,
    PRS: {
        'Custom 24': [],
        McCarty: [],
        509: [],
        Studio: [],
        'CE 24': [],
        S2: [],
        SE: [],
    } as Record<typeof model['PRS'][number], string[]>,
    Washburn: {
        Nuno: [],
        S10: [],
        S20: [],
        S2H: [],
        V26: [],
    } as Record<typeof model['Washburn'][number], string[]>,
    ESP: {
        Vintage: [],
        Kamikaze: [],
    } as Record<typeof model['ESP'][number], string[]>,
    Gretsch: {
        Falcon: [],
        G6: [],
    } as Record<typeof model['Gretsch'][number], string[]>,
    'G&L': {
        Asat: [],
        Commanche: [],
    } as Record<typeof model['G&L'][number], string[]>,
    Knaggs: {
        'Chop Tank': [],
        'Steve Stevens': [],
    } as Record<typeof model['Knaggs'][number], string[]>,
    Ibanez: {} as Record<typeof model['Ibanez'][number], string[]>,
    Epiphone: {
        'Les Paul': ['Standard', 'Custom', 'Special', 'Junior', 'Studio'],
        SG: [],
        Firebird: [],
        Explorer: [],
        'Flying V': [],
        M3: [],
    } as Record<typeof model['Epiphone'][number], string[]>,
    Schecter: {} as Record<typeof model['Schecter'][number], string[]>,
    Caparison: {
        Orbit: [],
    } as Record<typeof model['Caparison'][number], string[]>,
    Carvin: {
        DC: [],
        CS: [],
        AC: [],
    } as Record<typeof model['Carvin'][number], string[]>,
    Kiesel: {
        DC: [],
        CS: [],
        AC: [],
    } as Record<typeof model['Kiesel'][number], string[]>,
};

export default subModel;
