const subModel = {
    Fender: {
        Stratocaster: [
            'American Standard',
            'American Deluxe',
            'American Ultra',
            'American Elite',
            "American Original '50s",
            'American Vintage',
            'American Performer',
            'Hardtail',
            'VG',
            'Masterbuilt',
        ],
        Telecaster: [
            'American Vintage',
            'American Performer',
            'American Professional',
            'Thinline Semihollow',
            'Hot Rod',
            'Masterbuilt',
        ],
        Esquire: [],
        Nocaster: [],
        Jaguar: [],
        Jazzmaster: ['American Vintage'],
    },
    Gibson: {
        'Les Paul': ['Standard', 'Custom', 'Special', 'Junior', 'Studio'],
        SG: [],
        Firebird: ['I', 'III', 'V', 'VII'],
        Explorer: [],
        'Flying V': [],
        M3: [],
        'ES-335': [],
        'ES-347': [],
    },
    Jackson: {
        Dinky: [
            'DK1',
            'DK2',
            'DK2M',
            'DK2S',
            'DK2T',
            'DK2FF',
            'DK2FS',
            'DK3',
            'DR3',
            'DKMG',
            'DKMGT',
            'DXMG',
            'DKXT',
        ],
        Kelly: ['KE3', 'KE4', 'KV3'],
        'King V': [
            'KV',
            'KVT',
            'KV6',
            'KV7',
            'KV6Q',
            'KV7Q',
            'KVTMG',
            'KVXMG',
            'JS32',
            'JS32T',
        ],
        Monarkh: [],
        Rhoads: [],
        'San Dimas': [],
        'So-Cal': [],
        Soloist: ['SL1', 'SL2', 'SL2H', 'SLS', 'SL3', 'SL3R', 'SL3X'],
    },
    Charvel: {
        Dinky: [
            'DK1',
            'DK2',
            'DK2M',
            'DK2S',
            'DK2T',
            'DK2FF',
            'DK2FS',
            'DK3',
            'DR3',
            'DKMG',
            'DKMGT',
            'DXMG',
            'DKXT',
        ],
        Kelly: ['KE3', 'KE4', 'KV3'],
        'King V': [
            'KV',
            'KVT',
            'KV6',
            'KV7',
            'KV6Q',
            'KV7Q',
            'KVTMG',
            'KVXMG',
            'JS32',
            'JS32T',
        ],
        Monarkh: [],
        Rhoads: [],
        'San Dimas': [],
        'So-Cal': [],
        Soloist: ['SL1', 'SL2', 'SL2H', 'SLS', 'SL3', 'SL3R', 'SL3X'],
    },
    PRS: {
        'Custom 24': [],
        McCarty: [],
        509: [],
        Studio: [],
        CE24: [],
        S2: [],
        SE: [],
    },
    Washburn: {
        Nuno: [],
        S10: [],
        S20: [],
        S2H: [],
        V26: [],
    },
    ESP: {
        Vintage: [],
        Kamikaze: [],
    },
    Gretsch: {
        Falcon: [],
        G6: [],
    },
    'G&L': {
        Asat: [],
        Commanche: [],
    },
    Knaggs: {
        'Chop Tank': [],
        'Steve Stevens': [],
    },
    Ibanez: {},
    Epiphone: {
        'Les Paul': ['Standard', 'Custom', 'Special', 'Junior', 'Studio'],
        SG: [],
        Firebird: [],
        Explorer: [],
        'Flying V': [],
        M3: [],
    },
    Schecter: {},
    Caparison: {
        Orbit: [],
    },
    Carvin: {
        DC: [],
        CS: [],
        AC: [],
    },
    Kiesel: {
        DC: [],
        CS: [],
        AC: [],
    },
};

export default subModel;
