const model = {
    Fender: [
        'Stratocaster',
        'Telecaster',
        'Esquire',
        'Nocaster',
        'Jaguar',
        'Jazzmaster',
    ],
    Gibson: ['Les Paul', 'SG', 'Firebird', 'Explorer', 'Flying V', 'M3'],
    Jackson: [
        'Dinky',
        'Kelly',
        'King V',
        'Monarkh',
        'Rhoads',
        'San Dimas',
        'So-Cal',
        'Soloist',
    ],
    Charvel: [
        'Dinky',
        'Kelly',
        'King V',
        'Monarkh',
        'Rhoads',
        'San Dimas',
        'So-Cal',
        'Soloist',
    ],
    PRS: ['Custom 24', 'McCarty', '509', 'Studio', 'CE 24', 'S2', 'SE'],
    Washburn: ['Nuno', 'S10', 'S20', 'S2H', 'V26'],
    ESP: ['Vintage', 'Kamikaze'],
    Gretsch: ['Falcon', 'G6'],
    'G&L': ['Asat', 'Commanche'],
    Knaggs: ['Chop Tank', 'Steve Stevens'],
    Ibanez: [],
    Epiphone: ['Les Paul', 'SG', 'Firebird', 'Explorer', 'Flying V', 'M3'],
    Schecter: [],
    Caparison: ['Orbit'],
    Carvin: ['DC', 'CS', 'AC'],
    Kiesel: ['DC', 'CS', 'AC'],
};

export default model;
