const bridge = [
  'Tune-O-Matic',
  'Tune-O-Matic with Fine Tune Stoptail',
  'ABR-1 Tune-O-Matic',
  'Nashville Tune-O-Matic',
  'Locking Tune-O-Matic',
  'Tune-O-Matic with Locking Stoptail',
  'Locking Tune-O-Matic with Locking Stoptail',
  'Tone Pros Locking Tune-O-Matic with Locking Stoptail',
  'Compensated Wraparound',
  'Adjustable Wraparound',
  'Pigtail Adjustable Wraparound',
  'Schaller Adjustable Wraparound',
  'Tone Pros Adjustable Wraparound',
  'Maestro Vibrola',
  'Sideways Vibrola',
  'Fender Hardtail with Block Saddles',
  'Fender Hardtail with Bent Steel Saddles',
  'Fender 2-Point Deluxe Synchronized Tremolo',
  'Fender 2-Point Synchronized Tremolo with Bent Steel Saddles',
  'Fender 2-Point Synchronized Tremolo with Block Saddles',
  'Fender 2-Point Synchronized Tremolo with Vintage-Style Stamped Steel Saddles',
  'Fender Vintage-Style Standard Synchronized Tremolo',
  'Fender American Standard Stratocaster Tremolo',
  'Fender American Deluxe Stratocaster Tremolo',
  'Fender American Professional Stratocaster Tremolo',
  'Fender American Vintage Stratocaster Tremolo',
  'Fender 6-Saddle String-Through-Body Hardtail With Block Saddles',
  'Fender 3-Saddle American Vintage Strings-Through-Body Bridge with Intonateable Brass Saddles',
  'Vintage Telecaster Bridge with Compensated Brass Saddles',
  'Vintage Telecaster Bridge',
  'Floyd Rose 1000 Series Double Locking Tremolo',
  'Floyd Rose 2000 Series Double Locking Tremolo',
  'Licensed Floyd Rose Double Locking Tremolo',
  'Floyd Rose Original Double Locking Tremolo',
  'Floyd Rose Special Double Locking Tremolo',
  'Kahler 2200 Series Tremolo System',
  'Kahler 2300 Series Tremolo System',
  'Kahler 2400 Series Tremolo System',
  'Kahler 2500 Series Tremolo System',
  'Kahler 2600 Series Tremolo System',
  'Bigsby B-3 Vibrola',
  'Bigsby B-5 Vibrola',
  'Bigsby B-6 Vibrola',
  'Bigsby B-7 Vibrola',
  'Bigsby B-11 Vibrola',
  'Bigsby B-12 Vibrola',
  'Bigsby B-16 Vibrola',
  'Bigsby B-30 Vibrola',
  'Bigsby B-50 Vibrola',
  'Bigsby B-60 Vibrola',
  'Bigsby B-70 Vibrola',
  'Bigsby B-500 Vibrola',
  'Bigsby B-700 Vibrola',
] as const;

export const bridgeByBrand: { [key: string]: typeof bridge[number][] } = {
  Fender: [
    'Fender Hardtail with Block Saddles',
    'Fender Hardtail with Bent Steel Saddles',
    'Fender 2-Point Deluxe Synchronized Tremolo',
    'Fender 2-Point Synchronized Tremolo with Bent Steel Saddles',
    'Fender 2-Point Synchronized Tremolo with Block Saddles',
    'Fender 2-Point Synchronized Tremolo with Vintage-Style Stamped Steel Saddles',
    'Fender Vintage-Style Standard Synchronized Tremolo',
    'Fender American Standard Stratocaster Tremolo',
    'Fender American Deluxe Stratocaster Tremolo',
    'Fender American Professional Stratocaster Tremolo',
    'Fender American Vintage Stratocaster Tremolo',
    'Fender 6-Saddle String-Through-Body Hardtail With Block Saddles',
    'Fender 3-Saddle American Vintage Strings-Through-Body Bridge with Intonateable Brass Saddles',
    'Vintage Telecaster Bridge with Compensated Brass Saddles',
    'Vintage Telecaster Bridge',
  ],
  Gibson: [
    'ABR-1 Tune-O-Matic',
    'Tune-O-Matic',
    'Tune-O-Matic with Fine Tune Stoptail',
    'Locking Tune-O-Matic',
    'Tune-O-Matic with Locking Stoptail',
    'Locking Tune-O-Matic with Locking Stoptail',
    'Tone Pros Locking Tune-O-Matic with Locking Stoptail',
    'Compensated Wraparound',
    'Adjustable Wraparound',
    'Pigtail Adjustable Wraparound',
    'Schaller Adjustable Wraparound',
    'Tone Pros Adjustable Wraparound',
  ],
  Floyd: [
    'Floyd Rose 1000 Series Double Locking Tremolo',
    'Floyd Rose 2000 Series Double Locking Tremolo',
    'Licensed Floyd Rose Double Locking Tremolo',
    'Floyd Rose Original Double Locking Tremolo',
    'Floyd Rose Special Double Locking Tremolo',
  ],
  Kahler: [
    'Kahler 2200 Series Tremolo System',
    'Kahler 2300 Series Tremolo System',
    'Kahler 2400 Series Tremolo System',
    'Kahler 2500 Series Tremolo System',
    'Kahler 2600 Series Tremolo System',
  ],
  Bigsby: [
    'Bigsby B-3 Vibrola',
    'Bigsby B-5 Vibrola',
    'Bigsby B-6 Vibrola',
    'Bigsby B-7 Vibrola',
    'Bigsby B-11 Vibrola',
    'Bigsby B-12 Vibrola',
    'Bigsby B-16 Vibrola',
    'Bigsby B-30 Vibrola',
    'Bigsby B-50 Vibrola',
    'Bigsby B-60 Vibrola',
    'Bigsby B-70 Vibrola',
    'Bigsby B-500 Vibrola',
    'Bigsby B-700 Vibrola',
  ],
};

export default bridge.map((i) => i) as string[];
