const fingerBoardMaterial = [
  'Maple',
  'Rosewood',
  'Brazilian Rosewood',
  'Honduras Rosewood',
  'Indian Rosewood',
  'Ebony',
  'Macassar Ebony',
  'Brazilian Ebony',
  'African Ebony',
  'Pale Moon Ebony',
  'Flamed Maple',
  'Birdseye Maple',
  'Roasted Maple',
  'Pau Ferro',
  'Laurel',
  'Indian Laurel',
  'Wenge',
  'Walnut',
  'Blackwood',
  'African Blackwood',
  'Purpleheart',
  'Richlite',
];
export default fingerBoardMaterial;
