const frets = [
  '22 Medium Jumbo',
  '21 Medium Jumbo',
  '24 Medium Jumbo',
  '22 Medium',
  '21 Medium',
  '24 Medium',
  '22 Medium Tall',
  '21 Medium Tall',
  '24 Medium Tall',
  '22 Narrow Tall',
  '21 Narrow Tall',
  '24 Narrow Tall',
  '22 Jumbo',
  '21 Jumbo',
  '24 Jumbo',
  '22 Extra Jumbo',
  '21 Extra Jumbo',
  '24 Extra Jumbo',
  '22 Medium Jumbo Stainless',
  '21 Medium Jumbo Stainless',
  '24 Medium Jumbo Stainless',
  '22 Medium Stainless',
  '21 Medium Stainless',
  '24 Medium Stainless',
  '22 Medium Tall Stainless',
  '21 Medium Tall Stainless',
  '24 Medium Tall Stainless',
  '22 Narrow Tall Stainless',
  '21 Narrow Tall Stainless',
  '24 Narrow Tall Stainless',
  '22 Jumbo Stainless',
  '21 Jumbo Stainless',
  '24 Jumbo Stainless',
  '22 Extra Jumbo Stainless',
  '21 Extra Jumbo Stainless',
  '24 Extra Jumbo Stainless',
];

export default frets;
