const inlays = [
  'Acrylic Dot',
  'Pearloid Dot',
  'Abalone Dot',
  'Black Dot',
  'White Dot',
  'Mother of Pearl Dot',
  'Micarta Dot',
  'Acrylic Trapezoid',
  'Pearloid Trapezoid',
  'Abalone Trapezoid',
  'Black Trapezoid',
  'White Trapezoid',
  'Mother of Pearl Trapezoid',
  'Acrylic Block',
  'Pearloid Block',
  'Abalone Block',
  'Black Block',
  'White Block',
  'Mother of Pearl Block',
  'Acrylic Split Diamond',
  'Pearloid Split Diamond',
  'Abalone Split Diamond',
  'Black Split Diamond',
  'White Split Diamond',
  'Mother of Pearl Split Diamond',
  'Acrylic Sharkfin',
  'Pearloid Sharkfin',
  'Abalone Sharkfin',
  'Black Sharkfin',
  'White Sharkfin',
  'Mother of Pearl Sharkfin',
  'Acrylic Reverse Sharkfin',
  'Pearloid Reverse Sharkfin',
  'Abalone Reverse Sharkfin',
  'Black Reverse Sharkfin',
  'White Reverse Sharkfin',
  'Mother of Pearl Reverse Sharkfin',
  'Acrylic Piranha Tooth',
  'Pearloid Piranha Tooth',
  'Abalone Piranha Tooth',
  'Black Piranha Tooth',
  'White Piranha Tooth',
  'Mother of Pearl Piranha Tooth',
];

export default inlays;
