const model = {
  Fender: [
    'Stratocaster',
    'Telecaster',
    'Jaguar',
    'Jazzmaster',
    'Mustang',
    'Esquire',
    'Nocaster',
    'Broadcaster',
    'Starcaster',
    'Musicmaster',
    'P-Bass',
    'Jazz Bass',
  ],
  Squire: [
    'Stratocaster',
    'Telecaster',
    'Jaguar',
    'Jazzmaster',
    'Mustang',
    'Esquire',
    'Nocaster',
    'Broadcaster',
    'Starcaster',
    'Musicmaster',
    'P-Bass',
    'Jazz Bass',
  ],
  Gibson: [
    'Les Paul',
    'SG',
    'Firebird',
    'Explorer',
    'Flying V',
    'ES-335',
    'ES-345',
    'ES-339',
    'ES-347',
    'M3',
    'RD',
  ],
  Epiphone: [
    'Les Paul',
    'SG',
    'Firebird',
    'Explorer',
    'Flying V',
    'ES-335',
    'ES-345',
    'ES-339',
    'ES-347',
    'M3',
    'RD',
  ],
  Jackson: [
    'Soloist',
    'Dinky',
    'Kelly',
    'King V',
    'Rhoads',
    'Monarkh',
    'San Dimas',
    'So-Cal',
    'Chris Broderick',
  ],
  Charvel: [
    'Soloist',
    'Dinky',
    'Kelly',
    'King V',
    'Rhoads',
    'Monarkh',
    'San Dimas',
    'So-Cal',
    'Chris Broderick',
  ],
  PRS: ['Custom 24', 'McCarty', '509', 'Studio', 'CE 24', 'S2', 'SE'],
  'BC Rich': ['Warlock', 'Mockingbird', 'Beast', 'Bich'],
  Washburn: ['Nuno', 'S10', 'S20', 'S2H', 'V26'],
  ESP: [
    'Horizon',
    'Horizon II',
    'Eclipse',
    'Mirage',
    'M-I',
    'M-II',
    'Kirk Hammett',
    'KH-2',
    'JJ1',
    'Anchang Star',
    'George Lynch',
    'Super V',
    'Vulture',
  ],
  LTD: [
    'Horizon',
    'Eclipse',
    'EC',
    'EC-1000',
    'EC-FR',
    "Eclipse '87",
    'F',
    'GL-200',
    'MAX-200',
    'Mirage',
    'Phoenix',
    'Kirk Hammett',
    'Super V',
    'Vulture',
  ],
  Gretsch: ['Falcon', 'G6'],
  EVH: ['Wolfgang', 'Striped Series', '5150 Series'],
  'G&L': ['Asat', 'Commanche', 'Legacy'],
  Knaggs: ['Chop Tank', 'Steve Stevens'],
  Ibanez: [],
  Schecter: [],
  Caparison: ['Orbit'],
  Carvin: ['DC', 'CS', 'AC'],
  Kiesel: ['DC', 'CS', 'AC'],
  Yamaha: ['RGX', 'RG', 'RGA', 'RGT', 'RGR', 'RGC', 'RGE', 'RGA', 'RGT'],
  Kramer: ['Pacer', 'Striker', 'Baretta'],
} as const;

export default model;
