import tuningMachineBrands from './tuningMachineBrands';

const tuningMachineModels: {
  [key in typeof tuningMachineBrands[number]]: string[];
} = {
  Grover: [
    'Vintage',
    'Vintage Deluxe',
    'Mini Rotomatic',
    'Mini Locking Rotomatic',
    'Mini Locking Rotomatic 6-In-Line',
    'Original Rotomatic',
    'Original Locking Rotomatic',
    'Rotomatic',
    'Super Rotomatic',
    '"Milk Bottle" Rotomatic',
    'Rotomatic Locking',
    'Rotomatic 6-In-Line',
    'Mini Roto-Grip Locking Rotomatic',
    'Mini Roto-Grip Locking Rotomatic 6-In-Line',
    'Roto-Grip Locking Rotomatic',
    'Roto-Grip Locking Rotomatic 6-In-Line',
    'Sta-Tite Slotted Peghead',
  ],
  Gotoh: [
    'Large Schaller-Style',
    'Schaller-Style 6-In-Line',
    'Magnum Lock-Trad',
    'Magnum Lock-Trad 6-In-Line',
    'Midsize',
    'Mini',
    'Mini 6-In-Line',
    'Mini Locking 6-In-Line',
    'Staggered-Height 6-In-Line',
    'Vintage Style',
    'Vintage Style 6-In-Line',
    'Compact Bass',
  ],
  Fender: [
    'Locking 6-In-Line',
    'Left-Handed Locking 6-In-Line',
    'Road Worn 6-In-Line',
    'Deluxe 6-In-Line',
    'Deluxe Locking 6-In-Line',
    'Deluxe Staggered 6-In-Line',
    'Deluxe Staggered Locking 6-In-Line',
  ],
  Gibson: [
    'Vintage Deluxe',
    'Modern',
    'No Line Single Ring',
    'Single Line, Single Ring',
    'Single Line, Double Ring',
    'Double Line, Single Ring',
    'Double Line, Double Ring',
    'Patent Applied For',
  ],
  Jackson: ['Sealed Diecast'],
  Ibanez: [],
  'Hip Shot': [],
  Sperzel: ['Trim-Lok Locking', 'Trim-Lok 6-In-Line Locking'],
  Schaller: [
    'Locking',
    'Locking 6-In-Line',
    'M-6',
    'M-6 Mini',
    'M-6 Mini 6-In-Line',
  ],
  Kluson: [
    'Deluxe',
    'Locking Deluxe',
    'No Line, Single Ring Reissue',
    'Single Line, Double Ring Reissue',
    '6-In-Line Deluxe',
    '6-In-Line Locking Deluxe',
    '6-In-Line Diecast 2-Pin',
    '6-In-Line Locking Diecast 2-Pin',
    'Revolution',
    '6-In-Line Revolution',
    '6-In-Line Locking Revolution',
    'Supreme',
    '6-In-Line Supreme',
  ],
};

export default tuningMachineModels;
